/* This file was generated by `pkl-typescript` from Pkl module `01-primitiveTypes`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N01PrimitiveTypes {
  str: string

  int: number

  int8: number

  uint: number

  float: number

  bool: boolean

  nullType: null

  anyType: pklTypescript.Any

  nothingType: never
}
