// This file was generated by `pkl-typescript` from Pkl module `02-collections`.
// DO NOT EDIT.
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N02Collections {
  listingAny: Array<pklTypescript.Any>

  listingString: Array<string>

  mappingAny: Map<pklTypescript.Any, pklTypescript.Any>

  mappingStringString: Map<string, string>

  mappingStringInt: Map<string, number>

  listAny: Array<pklTypescript.Any>

  listString: Array<string>

  mapAny: Map<pklTypescript.Any, pklTypescript.Any>

  mapStringString: Map<string, string>

  mapStringInt: Map<string, number>

  setAny: Set<pklTypescript.Any>

  setString: Set<string>

  setInt: Set<number>
}

// LoadFromPath loads the pkl module at the given path and evaluates it into a N02Collections
export const loadFromPath = async (path: string): Promise<N02Collections> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<N02Collections> =>
  evaluator.evaluateModule(source) as Promise<N02Collections>;
