/* This file was generated by `pkl-typescript` from Pkl module `02-collections`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N02Collections {
  listingAny: Array<pklTypescript.Any>

  listingString: Array<string>

  mappingAny: Map<pklTypescript.Any, pklTypescript.Any>

  mappingStringString: Map<string, string>

  mappingStringInt: Map<string, number>

  listAny: Array<pklTypescript.Any>

  listString: Array<string>

  mapAny: Map<pklTypescript.Any, pklTypescript.Any>

  mapStringString: Map<string, string>

  mapStringInt: Map<string, number>

  setAny: Set<pklTypescript.Any>

  setString: Set<string>

  setInt: Set<number>
}
