/* This file was generated by `pkl-typescript` from Pkl module `03-nullables`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N03Nullables {
  nullableString: string|null

  nullableInt: number|null

  nullableListingOfStrings: Array<string>|null

  listingOfNullableStrings: Array<string|null>
}
