/* This file was generated by `pkl-typescript` from Pkl module `04-withClass`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N04WithClass {
  value: MyCustomClass
}

// Ref: Pkl class `04-withClass.MyCustomClass`.
export interface MyCustomClass {
  x: string

  y: number
}

// Ref: Pkl class `04-withClass.MyAbstractClass`.
export interface MyAbstractClass {
  someString: string

  overrideableStringType: string

  overridableListing1: Array<string | number>

  overridableListing2: Array<string | number>

  overridableMap1: Map<string, string | number>

  overridableMap2: Map<string, string | number>

  overridableUnion1: number | string | Array<string>

  overridableUnion2: number | string
}

// Ref: Pkl class `04-withClass.MyConcreteClass`.
export interface MyConcreteClass extends MyAbstractClass {
  anotherString: string

  overrideableStringType: "string literal type"

  overridableListing1: Array<number | string>

  overridableListing2: Array<string>

  overridableMap1: Map<string, number | string>

  overridableMap2: Map<string, string>

  overridableUnion1: string | number

  overridableUnion2: string
}
