// This file was generated by `pkl-typescript` from Pkl module `04-withClass`.
// DO NOT EDIT.
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N04WithClass {
  value: MyCustomClass
}

// Ref: Pkl class `04-withClass.MyCustomClass`.
export interface MyCustomClass {
  x: string

  y: number
}

// Ref: Pkl class `04-withClass.MyAbstractClass`.
export interface MyAbstractClass {
  someString: string
}

// Ref: Pkl class `04-withClass.MyConcreteClass`.
export interface MyConcreteClass extends MyAbstractClass {
  anotherString: string
}

// LoadFromPath loads the pkl module at the given path and evaluates it into a N04WithClass
export const loadFromPath = async (path: string): Promise<N04WithClass> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<N04WithClass> =>
  evaluator.evaluateModule(source) as Promise<N04WithClass>;
