/* This file was generated by `pkl-typescript` from Pkl module `05-withPair`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N05WithPair {
  x: pklTypescript.Pair<string, number>
}
