// This file was generated by `pkl-typescript` from Pkl module `05-withPair`.
// DO NOT EDIT.
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N05WithPair {
  x: readonly [string, number]
}

// LoadFromPath loads the pkl module at the given path and evaluates it into a N05WithPair
export const loadFromPath = async (path: string): Promise<N05WithPair> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<N05WithPair> =>
  evaluator.evaluateModule(source) as Promise<N05WithPair>;
