/* This file was generated by `pkl-typescript` from Pkl module `06-withTypeAlias`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N06WithTypeAlias {
  x: MyStringAlias

  y: MyAliasedClass
}

// Ref: Pkl class `06-withTypeAlias.MyClassToBeAliased`.
export interface MyClassToBeAliased {
  a: string

  b: number
}

// Ref: Pkl type `06-withTypeAlias.MyStringAlias`.
type MyStringAlias = string

// Ref: Pkl type `06-withTypeAlias.MyAliasedClass`.
type MyAliasedClass = MyClassToBeAliased
