/* This file was generated by `pkl-typescript` from Pkl module `06-withTypeAlias`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N06WithTypeAlias {
  x: MyStringAlias

  y: MyAliasedClass
}

// Ref: Pkl class `06-withTypeAlias.MyClassToBeAliased`.
export interface MyClassToBeAliased {
  a: string

  b: number
}

// Ref: Pkl type `06-withTypeAlias.MyStringAlias`.
type MyStringAlias = string

// Ref: Pkl type `06-withTypeAlias.MyAliasedClass`.
type MyAliasedClass = MyClassToBeAliased

// LoadFromPath loads the pkl module at the given path and evaluates it into a N06WithTypeAlias
export const loadFromPath = async (path: string): Promise<N06WithTypeAlias> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<N06WithTypeAlias> =>
  evaluator.evaluateModule(source) as Promise<N06WithTypeAlias>;
