/* This file was generated by `pkl-typescript` from Pkl module `07-literalTypes`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N07LiteralTypes {
  x: "one"

  y: "two"
}
