// This file was generated by `pkl-typescript` from Pkl module `07-literalTypes`.
// DO NOT EDIT.
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N07LiteralTypes {
  x: "one"

  y: "two"
}

// LoadFromPath loads the pkl module at the given path and evaluates it into a N07LiteralTypes
export const loadFromPath = async (path: string): Promise<N07LiteralTypes> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<N07LiteralTypes> =>
  evaluator.evaluateModule(source) as Promise<N07LiteralTypes>;
