/* This file was generated by `pkl-typescript` from Pkl module `09-customTypes`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N09CustomTypes {
  varAny: pklTypescript.Any

  varDymaic: pklTypescript.Dynamic

  varDataSizeUnit: pklTypescript.DataSizeUnit

  varDataSize: pklTypescript.DataSize

  varDuration: pklTypescript.Duration

  varIntSeq: pklTypescript.IntSeq

  varRegex: pklTypescript.Regex

  varPair: pklTypescript.Pair<string, number>
}

// LoadFromPath loads the pkl module at the given path and evaluates it into a N09CustomTypes
export const loadFromPath = async (path: string): Promise<N09CustomTypes> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<N09CustomTypes> =>
  evaluator.evaluateModule(source) as Promise<N09CustomTypes>;
