/* This file was generated by `pkl-typescript` from Pkl module `09-customTypes`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N09CustomTypes {
  varAny: pklTypescript.Any

  varDymaic: pklTypescript.Dynamic

  varDataSizeUnit: pklTypescript.DataSizeUnit

  varDataSize: pklTypescript.DataSize

  varDuration: pklTypescript.Duration

  varIntSeq: pklTypescript.IntSeq

  varRegex: pklTypescript.Regex

  varPair: pklTypescript.Pair<string, number>
}
