// This file was generated by `pkl-typescript` from Pkl module `11-withImport`.
// DO NOT EDIT.
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N11WithImport {
  value: ExampleClass
}

// Ref: Pkl class `moduleWithClass.ExampleClass`.
export interface ExampleClass {
  x: string

  y: number
}

// Ref: Module root.
export interface ModuleWithClass {
}

// LoadFromPath loads the pkl module at the given path and evaluates it into a N11WithImport
export const loadFromPath = async (path: string): Promise<N11WithImport> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<N11WithImport> =>
  evaluator.evaluateModule(source) as Promise<N11WithImport>;
