/* This file was generated by `pkl-typescript` from Pkl module `11-withImport`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N11WithImport {
  value: ExampleClass
}

// Ref: Pkl class `moduleWithClass.ExampleClass`.
export interface ExampleClass {
  x: string

  y: number
}

// Ref: Module root.
export interface ModuleWithClass {
}
