/* This file was generated by `pkl-typescript` from Pkl module `n10.pkl.typescript.tests.namedModule`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface NamedModule {
  x: string
}
