// This file was generated by `pkl-typescript` from Pkl module `n12.pkl.typescript.tests.moduleNameOverride`.
// DO NOT EDIT.
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N12TypescriptGeneratedInterface {
  classTypeProperty: MyCustomClassName

  typeAliasProperty: ThisTypeAlias
}

// Ref: Pkl class `n12.pkl.typescript.tests.moduleNameOverride.CustomClassImpl`.
export interface MyCustomClassName {
  name: string
}

// Ref: Pkl type `n12.pkl.typescript.tests.moduleNameOverride.AliasName`.
type ThisTypeAlias = "x" | "y" | MyCustomClassName

// LoadFromPath loads the pkl module at the given path and evaluates it into a N12TypescriptGeneratedInterface
export const loadFromPath = async (path: string): Promise<N12TypescriptGeneratedInterface> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<N12TypescriptGeneratedInterface> =>
  evaluator.evaluateModule(source) as Promise<N12TypescriptGeneratedInterface>;
