/* This file was generated by `pkl-typescript` from Pkl module `n12.pkl.typescript.tests.moduleNameOverride`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
export interface N12TypescriptGeneratedInterface {
  classTypeProperty: MyCustomClassName

  typeAliasProperty: ThisTypeAlias
}

// Ref: Pkl class `n12.pkl.typescript.tests.moduleNameOverride.CustomClassImpl`.
export interface MyCustomClassName {
  name: string
}

// Ref: Pkl type `n12.pkl.typescript.tests.moduleNameOverride.AliasName`.
type ThisTypeAlias = "x" | "y" | MyCustomClassName
