name: lint

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: "npm"

      - run: npm ci

      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v20
        with:
          reporter: github-check
          token: ${{ secrets.GITHUB_TOKEN }}

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: "npm"

      - run: npm ci

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38

      - run: npx prettier --check ${{ steps.changed-files.outputs.all_changed_files }}

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
