name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pkl-unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pklVersion: ["0.25.3", "0.26.3", "0.27.0"]

    steps:
      - uses: actions/checkout@v4

      - name: Install pkl
        uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: ${{ matrix.pklVersion }}

      - name: Run tests
        run: |
          tests=$(find ./codegen/src/ -name '*.test.pkl')
          # shellcheck disable=SC2086
          pkl test $tests

  pkl-snippet:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pklVersion: ["0.25.3", "0.26.3", "0.27.0"]

    steps:
      - uses: actions/checkout@v4

      - name: Install pkl
        uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: ${{ matrix.pklVersion }}

      - name: Run tests
        run: |
          pkl test codegen/snippet-tests/test.pkl

  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 21, 22, 23]
        pklVersion: ["0.25.3", "0.26.3", "0.27.0"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm install
      - run: npm run test:e2e
        timeout-minutes: 3
