name: codegen test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch Pkl binary from GitHub release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: apple/pkl
          # TODO: Parameterise version
          # TODO: Test on range of Pkl versions using matrix
          version: tags/0.25.1
          file: pkl-linux-amd64
          target: "{{ runner.temp }}/bin/pkl"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Make pkl binary executable
        run: chmod +x "{{ runner.temp }}/bin/pkl"

      - name: Run tests
        run: |
          tests=$(find . -name '*.test.pkl')
          pkl test $tests
