name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pkl-unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pklVersion: ["0.25.0", "0.25.1"]

    steps:
      - uses: actions/checkout@v2

      - name: Install pkl
        uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: ${{ matrix.pklVersion }}

      - name: Run tests
        run: |
          tests=$(find ./codegen/src/ -name '*.test.pkl')
          pkl test $tests

  pkl-snippet:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pklVersion: ["0.25.0", "0.25.1"]

    steps:
      - uses: actions/checkout@v2

      - name: Install pkl
        uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: ${{ matrix.pklVersion }}

      - name: Run tests
        run: |
          pkl test codegen/snippet-tests/test.pkl

  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]
        pklVersion: ["0.25.0", "0.25.1"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install pkl
        uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: ${{ matrix.pklVersion }}

      - run: npm install
      - run: npm run test:e2e
        timeout-minutes: 3
